apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: tarantula-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: tarantula-go 
  name: tarantula-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: tarantula-go 
